services:
  postgres:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=orderhere'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'