spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: orderhere
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}